### ISSUE TITLE
Dockerizing

### ISSUE THREAD

**Issue by bmikaili** [graphdeco-inria/gaussian-splatting#268]
Has anyone successfully dockerized this? I've found [this](https://gist.github.com/sergiobd/c9d133315da8a1045a743653dde1c65c), but it seems to only be for the viewer. I'm trying to dockerize it so that I can run it on a serverless GPU.

**Comment by ookami125** [comment]
I actually just did this over the weekend as running the colab in a jupyter notebook was failing due to a newer glibc version being needed. My version is here: https://github.com/ookami125/gaussian-splatting-docker/tree/docker up to this point I've been able to train a scene and view it.

**Comment by ookami125** [comment]
Seems this PR also exists, https://github.com/graphdeco-inria/gaussian-splatting/pull/163 I haven't tested it so YMMV.

**Comment by lachholden** [comment]
I've also had a crack at this for running on a remote Ubuntu server accessed with VNC:

**Dockerfile**
```Dockerfile
# Chosen to match the CUDA 11.7 installed on this machine
FROM nvidia/cuda:11.7.1-devel-ubuntu22.04

# Install dependencies
ENV DEBIAN_FRONTEND noninteractive
RUN apt update -y
RUN apt install -y build-essential wget

#  for viewers
RUN apt install -y libglew-dev libassimp-dev libboost-all-dev libgtk-3-dev libopencv-dev libglfw3-dev libavdevice-dev libavcodec-dev libeigen3-dev libxxf86vm-dev libembree-dev
RUN apt install -y cmake git

#  for training
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda
ENV PATH=$CONDA_DIR/bin:$PATH

#  for dataset conversion
RUN apt install -y colmap imagemagick

#  cleanup
RUN apt clean && rm -rf /var/lib/apt/lists/*

# Build viewers
COPY ./SIBR_viewers /gaussian-splatting-build/SIBR_viewers
WORKDIR /gaussian-splatting-build/SIBR_viewers

RUN cmake -Bbuild . -DCMAKE_BUILD_TYPE=Release
RUN cmake --build build -j24 --target install
ENV PATH=/gaussian-splatting-build/SIBR_viewers/install/bin:$PATH

# Setup Python environment
COPY ./environment.yml /gaussian-splatting-build/environment.yml
COPY ./submodules /gaussian-splatting-build/submodules
WORKDIR /gaussian-splatting-build
RUN conda env create --file environment.yml
RUN /bin/bash -c "conda init bash"
RUN echo "conda activate gaussian_splatting" >> /root/.bashrc

# Now mount the actual directory, hopefully
VOLUME /gaussian-splatting
WORKDIR /gaussian-splatting
```

**docker-compose.yml**
```yaml
version: "3.8"
services:
  splat:
    command: /bin/bash
    stdin_open: true
    tty: true
    build: .
    image: xxxxxxxxxx/gaussian-splatting:cuda-11.7
    network_mode: host
    environment:
      - DISPLAY
    volumes:
      - type: bind
        source: "${HOME}/.Xauthority"
        target: /root/.Xauthority
      - type: bind
        source: .
        target: /gaussian-splatting
      - type: bind
        source: "${HOME}/Datasets"
        target: /datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # count: 1
              device_ids: ['2']
              capabilities: [gpu]
```

Can then get into a console with
```shell
docker compose run --rm splat
```
and do all the `python train.py ...`, `python convert.py ...`, `SIBR_gaussianViewer_app ...` etc.

Works great for training, need to run viewers with `--no_interop` which makes them a bit laggy but is how I stopped getting a segmentation fault and I think that's the only option when attempting to run them remotely.
