### ISSUE TITLE
Installation using isolated cuda toolkit binaries within the conda environement

### ISSUE THREAD

**Issue by martinResearch** [graphdeco-inria/gaussian-splatting#823]
The current installation process described in the README file requires the user to install the CUDA Toolkit SDK at the system level. This is not ideal as it can potentially interfere with other environments created for other projects that require a different version of the CUDA Toolkit. It also complicates the installation procedure by requiring a manual CUDA Toolkit installation step.

The CUDA Toolkit, including `nvcc.exe`, can instead be installed in isolation within the conda environment using the conda `cuda-toolkit` package from https://anaconda.org/nvidia/cuda-toolkit.

We can use this `environment.yml` file to simplify the installation by removing the need to manually install the CUDA Toolkit SDK and get a self-contained environment:
```
name: gaussian_splatting
channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit 
  - plyfile
  - python=3.7.13
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
variables:
  DISTUTILS_USE_SDK: 1
  CUDA_PATH: ""
```
One caveat with this approach is that one needs to remove the CUDA_PATH system-level environement variable  if it exists or run `set CUDA_PATH=` before calling `conda env create --file environment.yml` to ignore the system-wide CUDA_PATH environement variable, otherwise pytorch will look for nvcc and the cuda dlls in the CUDA_PATH folder instead of the folder in the conda environment and fail with a very uninformative "[WinError 2] The system cannot find the file specified" error message.

One possibility to limit the risk of getting an error when doing the installation on windows could be to add a `install_on_windows.bat` file in the repository root that contains
```
set DISTUTILS_USE_SDK= 1
set CUDA_PATH=
call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"   
conda env create --file environment.yml
```
 Would could have similar script for Linux.
 Would it be possible to add these changes to the repository?
